{% set name = "sphinx-notfound-page" %}
{% set version = "1.0.0" %}
{% set hash = "14cd388956de5cdf8710ab4ff31776ef8d85759c4f46014ee30f368e83bd3a3b" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - flit-core >=3.2,<4
  run:
    - python >=3
    - sphinx
    - docutils

test:
  imports:
    - notfound
    - notfound.extension

about:
  home: https://github.com/readthedocs/sphinx-notfound-page
  license: MIT
  license_file: LICENSE
  summary: Create a custom 404 page with absolute URLs hardcoded
  doc_url: https://sphinx-notfound-page.readthedocs.io
  dev_url: https://github.com/readthedocs/sphinx-notfound-page

extra:
  recipe-maintainers:
    - astamminger
    - chrisjsewell
